FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY packages/tr-api-errors packages/tr-api-errors
COPY apps/courier/package.json apps/courier/package.json
RUN pnpm install --filter @pastane/courier... --no-frozen-lockfile --shamefully-hoist
RUN pnpm --filter @pastane/tr-api-errors build
COPY apps/courier apps/courier
ENV RUNNING_IN_DOCKER=1
EXPOSE 3002
RUN chown -R node:node /app
USER node
CMD ["pnpm", "--filter", "@pastane/courier", "dev"]
