FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY packages/tr-api-errors packages/tr-api-errors
COPY apps/web/package.json apps/web/package.json
RUN pnpm install --filter @pastane/web... --no-frozen-lockfile --shamefully-hoist
RUN pnpm --filter @pastane/tr-api-errors build
COPY apps/web apps/web
ENV RUNNING_IN_DOCKER=1
EXPOSE 3000
RUN chown -R node:node /app
USER node
CMD ["pnpm", "--filter", "@pastane/web", "dev"]
