import { DeliveryStatus, OrderStatus } from '@prisma/client';
import { OrderStatusService } from '../orders/order-status.service';
import { DeliveryStatusService } from './delivery-status.service';
import { DeliveriesService } from './deliveries.service';
describe('DeliveriesService',()=> {
  it('owner-scopes courier delivery detail queries',async()=>{const findFirst=jest.fn().mockResolvedValue({id:'delivery-1'}); const service=new DeliveriesService({delivery:{findFirst}} as never,new DeliveryStatusService(),new OrderStatusService(),{log:jest.fn()} as never,{earnForDeliveredOrder:jest.fn()} as never,{createOrderStatusNotification:jest.fn()} as never); await service.getMine('user-1','delivery-1'); expect(findFirst).toHaveBeenCalledWith(expect.objectContaining({where:{id:'delivery-1',courier:{userId:'user-1',deletedAt:null},order:{deletedAt:null}}}))});
  it('updates delivery and order together when picked up',async()=>{const tx={delivery:{findFirst:jest.fn().mockResolvedValue({id:'delivery-1',orderId:'order-1',status:DeliveryStatus.ASSIGNED,order:{id:'order-1',status:OrderStatus.ASSIGNED_TO_COURIER}}),update:jest.fn().mockResolvedValue({id:'delivery-1'})},order:{update:jest.fn()},orderStatusHistory:{create:jest.fn()}}; const service=new DeliveriesService({$transaction:jest.fn(fn=>fn(tx))} as never,new DeliveryStatusService(),new OrderStatusService(),{log:jest.fn()} as never,{earnForDeliveredOrder:jest.fn()} as never,{createOrderStatusNotification:jest.fn()} as never); await service.pickUp('user-1','delivery-1'); expect(tx.delivery.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:DeliveryStatus.PICKED_UP})})); expect(tx.order.update).toHaveBeenCalledWith({where:{id:'order-1'},data:{status:OrderStatus.OUT_FOR_DELIVERY}})});
  it('syncs order when delivery fails',async()=>{const notify=jest.fn(); const tx={delivery:{findFirst:jest.fn().mockResolvedValue({id:'delivery-1',orderId:'order-1',status:DeliveryStatus.PICKED_UP,order:{id:'order-1',status:OrderStatus.OUT_FOR_DELIVERY,userId:'user-c',orderNumber:'P-1'}}),update:jest.fn().mockResolvedValue({id:'delivery-1'})},order:{update:jest.fn()},orderStatusHistory:{create:jest.fn()}}; const service=new DeliveriesService({$transaction:jest.fn(fn=>fn(tx))} as never,new DeliveryStatusService(),new OrderStatusService(),{log:jest.fn()} as never,{earnForDeliveredOrder:jest.fn()} as never,{createOrderStatusNotification:notify} as never); await service.fail('user-1','delivery-1',{reason:'  Müşteri adreste yok  '}); expect(tx.delivery.update).toHaveBeenCalledWith({where:{id:'delivery-1'},data:{status:DeliveryStatus.FAILED,failedReason:'Müşteri adreste yok'}}); expect(tx.order.update).toHaveBeenCalledWith({where:{id:'order-1'},data:{status:OrderStatus.DELIVERY_FAILED}}); expect(tx.orderStatusHistory.create).toHaveBeenCalledWith({data:{orderId:'order-1',status:OrderStatus.DELIVERY_FAILED,note:'Müşteri adreste yok'}}); expect(notify).toHaveBeenCalledWith(tx,'user-c','P-1','Teslim edilemedi')});
});
