user nginx;
worker_processes auto;

events { worker_connections 1024; }

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    "" close;
  }

  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "no-referrer-when-downgrade" always;
  client_max_body_size 20M;
  limit_req_zone $binary_remote_addr zone=pastane_auth:10m rate=10r/m;
  limit_req_zone $binary_remote_addr zone=pastane_api:10m rate=100r/m;
  include /etc/nginx/conf.d/*.conf;
}
