FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json .npmrc ./
COPY packages/tr-api-errors packages/tr-api-errors
COPY packages/ui packages/ui
COPY apps/admin/package.json apps/admin/package.json
RUN pnpm install --filter @pastane/admin... --no-frozen-lockfile --shamefully-hoist
RUN pnpm --filter @pastane/tr-api-errors --filter @pastane/ui build
COPY apps/admin apps/admin
ENV RUNNING_IN_DOCKER=1
EXPOSE 3001
RUN chown -R node:node /app
USER node
CMD ["pnpm", "--filter", "@pastane/admin", "dev"]
