import { HttpStatus, Inject, Injectable } from '@nestjs/common';
import { PrismaService } from '../database/prisma.service'; import { AppException } from '../common/exceptions/app.exception'; import { ERROR_CODES } from '../common/constants/error-codes'; import { slugify } from '../common/utils/slug.util'; import type { CreateCategoryDto } from './dto/create-category.dto'; import type { UpdateCategoryDto } from './dto/update-category.dto';
@Injectable() export class CategoriesService { constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
 async tree(){ const rows=await this.prisma.category.findMany({where:{deletedAt:null,isActive:true},orderBy:[{sortOrder:'asc'},{name:'asc'}]}); const map=new Map(rows.map(x=>[x.id,{...x,children:[] as typeof rows}])); const roots: Array<Record<string, unknown>>=[]; for(const row of rows){ const node=map.get(row.id)!; if(row.parentId&&map.has(row.parentId)) map.get(row.parentId)!.children.push(node as never); else roots.push(node);} return roots; }
 async get(id:string){ const row=await this.prisma.category.findFirst({where:{id,deletedAt:null},include:{children:{where:{deletedAt:null}},products:{where:{deletedAt:null}}}}); if(!row) throw new AppException(ERROR_CODES.CATEGORY_NOT_FOUND,'Category not found',HttpStatus.NOT_FOUND); return row; }
 async getBySlug(slug:string){ const row=await this.prisma.category.findFirst({where:{slug,deletedAt:null,isActive:true},include:{children:{where:{deletedAt:null,isActive:true}},products:{where:{deletedAt:null,status:'ACTIVE'}}}}); if(!row) throw new AppException(ERROR_CODES.CATEGORY_NOT_FOUND,'Category not found',HttpStatus.NOT_FOUND); return row; }
 async create(dto:CreateCategoryDto){ if(dto.parentId) await this.get(dto.parentId); const slug=await this.uniqueSlug(dto.name); return this.prisma.category.create({data:{...dto,slug}}); }
 async update(id:string,dto:UpdateCategoryDto){ await this.get(id); if(dto.parentId===id) throw new AppException(ERROR_CODES.VALIDATION_FAILED,'Category cannot be its own parent',HttpStatus.BAD_REQUEST); if(dto.parentId) await this.get(dto.parentId); const data={...dto,...(dto.name?{slug:await this.uniqueSlug(dto.name,id)}:{})}; return this.prisma.category.update({where:{id},data}); }
 async remove(id:string){ await this.get(id); const count=await this.prisma.product.count({where:{categoryId:id,deletedAt:null}}); if(count) throw new AppException(ERROR_CODES.CATEGORY_HAS_PRODUCTS,'Category has products',HttpStatus.BAD_REQUEST); return this.prisma.category.update({where:{id},data:{deletedAt:new Date(),isActive:false}}); }
 private async uniqueSlug(name:string,excludeId?:string){ const base=slugify(name); let slug=base; let i=2; while(await this.prisma.category.findFirst({where:{slug,...(excludeId?{id:{not:excludeId}}:{})}})){ slug=`${base}-${i++}`;} return slug; }
}
