FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml turbo.json tsconfig.base.json eslint.config.mjs ./
COPY apps/api/package.json apps/api/package.json
COPY packages/database/package.json packages/database/package.json
COPY packages/database/schema.prisma packages/database/schema.prisma
COPY packages/database/migrations packages/database/migrations
COPY packages/database/prisma packages/database/prisma
RUN pnpm install --filter @pastane/api... --filter @pastane/database... --no-frozen-lockfile
RUN pnpm --filter @pastane/database prisma:generate
COPY apps/api apps/api
EXPOSE 3003
CMD ["pnpm", "--filter", "@pastane/api", "dev"]
